image: node:latest

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - npm i
    - npx tailwindcss -i ./public/input.css -o ./public/output.css --minify
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
